SELECT
        TRIM(CO_CHG_CONTROL_NBR)                         AS CO_CHG_CONTROL_NBR,
        TRIM(CO_TYPE)                                                AS CO_TYPE,
        TRIM(CO_DESCRIPTION)                                AS CO_DESCRIPTION,
        TRIM(CO_PRODUCT_LINE)                                AS CO_PRODUCT_LINE,
        TRIM(CO_ORIGINATION_DEPT)                        AS CO_ORIGINATION_DEPT,
        TRIM(CO_ORIGINATOR)                                        AS CO_ORIGINATOR,
        CAST(NULL AS DATE)                                         AS CO_ORIGINATION_DATE,
        TRIM(CO_CLASS_CODE)                                        AS CO_CLASS_CODE,
        TRIM(CO_REASON_CODE)                                AS CO_REASON_CODE,
        TRIM(CO_SEVERITY_CODE)                                AS CO_SEVERITY_CODE,
        TRIM(CO_CONSOLIDATING_IND)                        AS CO_CONSOLIDATING_IND,
        CAST(NULL AS DATE)                                         AS CO_PLANNED_EFF_DATE,
        TRIM(CO_PLANNED_EFF_SERIAL_NBR)                AS CO_PLANNED_EFF_SERIAL_NBR,
        TRIM(CO_MOD_INCORPORACION)                        AS CO_MOD_INCORPORACION,
        TRIM(CO_IND_PM_ASOCIADOS)                        AS CO_IND_PM_ASOCIADOS,
        TRIM(CO_INDICE_REV_MOD)                                AS CO_INDICE_REV_MOD,
        TRIM(CO_INTERCAMBIAR)                                AS CO_INTERCAMBIAR,
        TRIM(CO_STATUS_IND)                                        AS CO_STATUS_IND,
        CAST(NULL AS DATE)                                         AS CO_ACTUAL_RLSE_TO_DESIGN_DATE,
        CAST(NULL AS DATE)                                         AS CO_TARGET_RLSE_TO_DESIGN_DATE,
        CAST(NULL AS DATE)                                         AS CO_ACTUAL_ASSIGN_TO_CM_DATE,
        CAST(NULL AS DATE)                                         AS CO_TARGET_ASSIGN_TO_CM_DATE,
        CAST(NULL AS DATE)                                         AS CO_ACTUAL_RLSE_FOR_APPR_DATE,
        CAST(NULL AS DATE)                                         AS CO_TARGET_RLSE_FOR_APPR_DATE,
        CAST(NULL AS DATE)                                         AS CO_ACTUAL_APPROVAL_DATE,
        CAST(NULL AS DATE)                                         AS CO_TARGET_APPROVAL_DATE,
        CAST(NULL AS DATE)                                         AS CO_ACTUAL_INCORP_DATE,
        CAST(NULL AS DATE)                                         AS CO_TARGET_INCORP_DATE,
        TRIM(CO_DISPOSITION_CODE)                        AS CO_DISPOSITION_CODE,
        CAST(NULL AS DATE)                                         AS CO_DISPOSITION_DATE,
        TRIM(CO_PROG)                                                AS CO_PROG,
        TRIM(CO_ELEM_FINAL)                                        AS CO_ELEM_FINAL,
        TRIM(CO_IND_COSTE_MOD)                                AS CO_IND_COSTE_MOD,
        TRIM(CO_COSTE_ESTIM_MOD)                        AS CO_COSTE_ESTIM_MOD,
        TRIM(CO_ACCION_TOMADA)                                AS CO_ACCION_TOMADA,
        TRIM(CO_LANZAM_TOT)                                        AS CO_LANZAM_TOT,
        TRIM(CO_LANZAM_CUMPL)                                AS CO_LANZAM_CUMPL,
        TRIM(CO_FECHA_ING_PREV)                                AS CO_FECHA_ING_PREV,
        TRIM(CO_FECHA_ING_REAL)                                AS CO_FECHA_ING_REAL,
        TRIM(CO_FECHA_OCT_PREV)                                AS CO_FECHA_OCT_PREV,
        TRIM(CO_FECHA_OCT_REAL)                                AS CO_FECHA_OCT_REAL,
        TRIM(CO_FECHA_TERM_PREV)                        AS CO_FECHA_TERM_PREV,
        TRIM(CO_FECHA_TERM_REAL)                        AS CO_FECHA_TERM_REAL,
        TRIM(CO_ORIGIN)                                                AS CO_ORIGIN,
        TRIM(CO_AFECTACION)                                        AS CO_AFECTACION,
        ROWID                                                                 AS rid
FROM  CDC_ND72.COMAST
WHERE CO_PROG = 'K'