SELECT
        TRIM(CG_LP_CONCAT_KEY)                                                                                 AS CG_LP_CONCAT_KEY,
        TRIM(CG_ASSY_PART_NBR)                                                                                 AS CG_ASSY_PART_NBR,
        TRIM(CG_LINE)                                                                                                 AS CG_LINE,
        TRIM(CG_COMP_PART_NBR)                                                                                 AS CG_COMP_PART_NBR,
        TRIM(CG_COMP_TYPE)                                                                                         AS CG_COMP_TYPE,
        TRIM(CG_COMP_USAGE)                                                                                 AS CG_COMP_USAGE,
        TRIM(CAST(CG_QTY_PER AS VARCHAR2(10)))                                 AS CG_QTY_PER,
        TRIM(CG_QTY_TYPE)                                                                                         AS CG_QTY_TYPE,
        TRIM(CAST(CG_DECIMAL_CODE AS VARCHAR2(1)))                                AS CG_DECIMAL_CODE,
        TRIM(CAST(CG_OPT_PCT AS VARCHAR2(2)))                                         AS CG_OPT_PCT,
        TRIM(CG_REVISION_IN)                                                                                 AS CG_REVISION_IN,
        CAST(NULL AS DATE)                                                                                         AS CG_EFFECT_DATE_IN,
        TRIM(CG_PEND_REV_IN)                                                                                 AS CG_PEND_REV_IN,
        CAST(NULL AS DATE)                                                                                         AS CG_APPROVAL_DATE_IN,
        TRIM(CG_LAST_INC_REV)                                                                                 AS CG_LAST_INC_REV,
        CAST(NULL AS DATE)                                                                                  AS CG_INC_REV_DATE_IO,
        TRIM(CG_REVISION_OUT)                                                                                 AS CG_REVISION_OUT,
        CAST(NULL AS DATE)                                                                                  AS CG_EFFECT_DATE_OUT,
        TRIM(CG_PEND_REV_OUT)                                                                                 AS CG_PEND_REV_OUT,
        CAST(NULL AS DATE)                                                                                  AS CG_APPROVAL_DATE_OUT,
        CAST(NULL AS DATE)                                                                                         AS CG_DE_DATE_MAX,
        TRIM(CAST(CG_LOW_LEVEL_CODE AS VARCHAR2(5)))                         AS CG_LOW_LEVEL_CODE,
        TRIM(CG_REVISION_TYPE_IN)                                                                         AS CG_REVISION_TYPE_IN,
        substr(TRIM(CAST(CG_EFFECT_SERIAL_NBR_IN AS VARCHAR2(10))),-5) AS CG_EFF_SERIAL_NBR_IN_VALID,
        TRIM(CAST(CG_EFFECT_SERIAL_NBR_IN AS VARCHAR2(10)))        AS CG_EFFECT_SERIAL_NBR_IN,
        TRIM(CG_REVISION_TYPE_OUT)                                                                         AS CG_REVISION_TYPE_OUT,
        substr(TRIM(CAST(CG_EFFECT_SERIAL_NBR_OUT AS VARCHAR2(10))),-5) AS CG_EFF_SERIAL_NBR_OUT_VALID,
        TRIM(CAST(CG_EFFECT_SERIAL_NBR_OUT AS VARCHAR2(10)))         AS CG_EFFECT_SERIAL_NBR_OUT,
        TRIM(CAST(CG_ECS_COUNT AS VARCHAR2(10)))                                 AS CG_ECS_COUNT,
        TRIM(CAST(CG_ALT_GRP_CODE AS VARCHAR2(5)))                         AS CG_ALT_GRP_CODE,
        TRIM(CAST(CG_ALT_PREF_CODE AS VARCHAR2(5)))                         AS CG_ALT_PREF_CODE,
        TRIM(CG_POS_EN_PLANO)                                                                                 AS CG_POS_EN_PLANO,
        TRIM(CAST(CG_NUM_ITEM AS VARCHAR2(5)))                                 AS CG_NUM_ITEM,
        TRIM(CAST(CG_IND_EXCEPT AS VARCHAR2(5)))                                 AS CG_IND_EXCEPT,
        TRIM(CG_AC_DISTINTIVO)                                                                                 AS CG_AC_DISTINTIVO,
        TRIM(CG_PROG_OBRA_IN)                                                                                 AS CG_PROG_OBRA_IN,
        TRIM(CG_PROG_OBRA_OUT)                                                                                 AS CG_PROG_OBRA_OUT,
        TRIM(CG_NOM_MODULO_IN)                                                                                 AS CG_NOM_MODULO_IN,
        TRIM(CG_NOM_MODULO_OUT)                                                                         AS CG_NOM_MODULO_OUT,
        TRIM(CG_MODIF_IN)                                                                                         AS CG_MODIF_IN,
        TRIM(CG_MODIF_OUT)                                                                                         AS CG_MODIF_OUT,
        TRIM(CG_DIMENSIONES)                                                                                 AS CG_DIMENSIONES,
        TRIM(CG_STR_REPL_SUPR_IND)                                                                         AS CG_STR_REPL_SUPR_IND,
        TRIM(CG_COMP_ALTERNATIVO)                                                                         AS CG_COMP_ALTERNATIVO,
        CG_INCORPOR_DATE_IN                                                                                  AS CG_INCORPOR_DATE_IN,
        CG_INCORPOR_DATE_OUT                                                                                  AS CG_INCORPOR_DATE_OUT,
    CAST(CASE 
                WHEN ((NVL(CG_INCORPOR_DATE_IN,0) >= 0) AND (NVL(CG_INCORPOR_DATE_OUT,0) > 0))
            THEN 'IS_REL' 
                WHEN (NVL(CG_INCORPOR_DATE_IN,0) = 0 AND NVL(CG_INCORPOR_DATE_OUT,0) = 0 )
                THEN 'IS_LAST_WIP'
                WHEN (NVL(CG_INCORPOR_DATE_IN,0) > 0 AND NVL(CG_INCORPOR_DATE_OUT,0) = 0 )
                THEN 'IS_BOTH' END AS VARCHAR2(15))                                         AS FILTER_ISSUE,
        ROWID                                                                                                                 AS rid
FROM CDC_ND72.CONFIG